### ISSUE TITLE
请问 update_locales.py 需要的 python 环境是 2 还是 3？

### ISSUE THREAD

**Issue by fafaraway** [fang2hou/WindToolsScripts#1]
我的 python 环境是 3.9.6，执行后没有报错也没有输出 🐶

**Comment by fang2hou** [comment]
`update_locales.py` 只是包含了一些方法, 具体的话还是要去用另外一个文件或者自己在下面加一点代码, 毕竟每个项目的语言文件管理方式都有点差异.

文件里面也有写了一些样例, https://github.com/fang2hou/WindToolsScripts/blob/c986182ca4f03457c5ef942eee0a6505e6871248/UpdateTranslations/update_locales.py#L109
同时可以参考这个脚本 https://github.com/fang2hou/WindToolsScripts/blob/master/UpdateTranslations/merathilis_ui.py

**Comment by fang2hou** [comment]
环境的话默认是 `Python 3.5+`
我自己用的一些脚本在https://github.com/fang2hou/WindToolsScripts/tree/c986182ca4f03457c5ef942eee0a6505e6871248/MergeLocales

**Comment by fafaraway** [comment]
我是完全照搬你的脚本的，只是更改了插件目录

**Comment by fafaraway** [comment]
啊，弄明白了，要使用 `Conda`

**Comment by fafaraway** [comment]
一切正常，感谢大佬，这个脚本真是救了命了 👍

**Comment by fang2hou** [comment]
嗯, 有个要提醒一下就是我习惯中文翻译也用英文标点, 比较整齐.
https://github.com/fang2hou/WindToolsScripts/blob/c986182ca4f03457c5ef942eee0a6505e6871248/MergeLocales/update_locales.py#L102
可以自行改动一下这里, 就能去掉这个替换.
